Blog.WebUI/Entities/Blog.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Entities
{
    public class Blog
    {
        public int BlogId { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Image { get; set; }
        [BindNever]
        public DateTime Date { get; set; }
        public bool IsApproved { get; set; }
        public bool IsHome { get; set; }
        public bool IsSlider { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

Blog.WebUI/Entities/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Entities
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public List<Blog> Blogs { get; set; }
    }
}

Blog.WebUI/Models/BlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Models
{
    public class BlogModel
    {
    }
}

Blog.WebUI/Models/HomeBlogModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Models
{
    public class HomeBlogModel
    {
        public List<Entities.Blog> SliderBlogs { get; set; }
        public List<Entities.Blog> HomeBlogs { get; set; }
    }
}

Blog.WebUI/Controllers/BlogController.cs
using Blog.WebUI.Abstraction;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
namespace Blog.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        private ICategoryRepository _categoryRepository;
        public BlogController(IBlogRepository _blog, ICategoryRepository category)
        {
            _blogRepository = _blog;
            _categoryRepository = category;
        }
        public IActionResult Index(int? id, string q)
        {
            var query = _blogRepository.GetAll().Where(i => i.IsApproved);
            if (id != null)
            {
                query = query.Where(i => i.CategoryId == id);
            }
            if (!string.IsNullOrEmpty(q))
            {
                query = query.Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q));
            }
            return View(query.OrderByDescending(i => i.Date));
        }
        public IActionResult List()
        {
            return View(_blogRepository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Entities.Blog blog)
        {
            blog.Date = DateTime.Now;
            blog.IsApproved = true;
            if (ModelState.IsValid)
            {
                _blogRepository.AddBlog(blog);
                return RedirectToAction("List");
            }
            return View(blog);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(_blogRepository.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Details(Entities.Blog blog, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", file.FileName);
                    using (var s = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(s);
                    }
                    blog.Image = file.FileName;
                }

                _blogRepository.UpdateBlog(blog);
                TempData["message"] = $" {blog.Title} was updated . . . ";
                return RedirectToAction("List");
            }
            return View(blog);
        }
        public IActionResult Delete(int id)
        {
            return View(_blogRepository.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _blogRepository.DeleteBlog(id);
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult ShowMore(int id)
        {

            return View(_blogRepository.GetById(id));
        }
    }
}

Blog.WebUI/Controllers/CategoryController.cs
using Blog.WebUI.Abstraction;
using Blog.WebUI.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.Controllers
{
    public class CategoryController:Controller
    {
        private ICategoryRepository repository;

        public CategoryController(ICategoryRepository repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            return View(repository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                repository.AddCategory(category);
                return RedirectToAction("List");
            }
            return View(category);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(repository.GetById(id));
        }
        [HttpPost]
        public IActionResult Details(Category category)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateCategory(category);
                TempData["message"] = $" {category.Name} was updated . . . ";
                return RedirectToAction("List");
            }
            return View(category);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(repository.GetById(id));
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            repository.DeleteCategory(id);
            return RedirectToAction("List");
        }
    }
}

Blog.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.WebUI.Abstraction;
using Blog.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Blog.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository blogRepository;

        public HomeController(IBlogRepository blogRepository)
        {
            this.blogRepository = blogRepository;
        }

        public IActionResult Index()
        {
            HomeBlogModel model = new HomeBlogModel();
            model.HomeBlogs = blogRepository.GetAll().Where(i => i.IsApproved == true && i.IsHome == true).ToList();
            model.SliderBlogs = blogRepository.GetAll().Where(i => i.IsApproved == true && i.IsSlider == true).ToList();
            return View(model);
        }
        public IActionResult Details()
        {

            return View();
        }
        public IActionResult List()
        {
            return View();
        }
    }
}

Blog.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using Blog.WebUI.Abstraction;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent:ViewComponent
    {
        private ICategoryRepository _repo;

        public CategoryMenuViewComponent(ICategoryRepository repo)
        {
            _repo = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(_repo.GetAll());
        }
    }
}

Blog.WebUI/Views/Blog/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">

    <h1>Create</h1>
    <br />
    <form asp-controller="Blog" asp-action="Create" method="post">

        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
      
        
        
        <div class="form-group">
            <label asp-for="CategoryId">CategoryId</label>
            <select class="form-group" asp-for="CategoryId" asp-items="ViewBag.Categories">
                <option disabled>Select Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Blog.WebUI/Views/Blog/Delete.cshtml
@model Blog
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>
    Do you want to delete 
    <b>

    @Model.Title
    </b> ?
    </h1>

<form asp-controller="blog" asp-action="Delete" method="post">
    <input type="hidden" asp-for="BlogId" />
    <button type="submit" class="btn btn-primary" >Delete</button>
</form>

Blog.WebUI/Views/Blog/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

    <div class="container">

        <h1>Edit</h1>
        <br />


        <form asp-controller="Blog" asp-action="Details" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="BlogId" />
            <input type="hidden" asp-for="Image"/>
            <div class="form-group " style="width:auto;margin:auto;text-align:center;">
                <img src="~/images/@Model.Image"
                     style="width:200px;height:200px;border-radius:50%;box-shadow:10px 10px 15px #00bfff;
" />
                <input type="file" id="file" name="file" class="form-control mt-3 mb-3" />
            </div>
            <div class="form-group">
                <label asp-for="Title">Title</label>
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Body">Body</label>
                <textarea asp-for="Body" class="form-control"></textarea>
            </div>



            <div class="form-check">
                <label class="form-check-label">
                    <input asp-for="IsApproved" class="form-check-input" />
                    IsApproved
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input asp-for="IsHome" class="form-check-input" />
                    IsHome
                </label>
            </div>
            <div class="form-check">
                <label class="form-check-label">
                    <input asp-for="IsSlider" class="form-check-input" />
                    IsSlider
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId">CategoryId</label>
                <select class="form-group" asp-for="CategoryId" asp-items="ViewBag.Categories">
                    <option disabled>Select Category</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

Blog.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Index";
}
<div class="container mt-3">

    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList", Model)
        </div>
    </div>
</div>

Blog.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container mt-3">
    <h2>Blog List</h2>
    <hr/>
    <div class="mb-2 mt-2">
        <a class="btn btn-secondary btn-outline-dark" href="/blog/create">Create</a>
    </div>
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Is Approved</th>
                            <th>Is From Home</th>
                            <th>Is Slider </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.BlogId</td>
                            <td>
                                <img style="border-radius:50%;" src="~/images/@item.Image" width="200" height="200" />
                            </td>
                            <td>@item.Title</td>
                            <td>@item.Date</td>
                            <td>

                                @if (item.IsApproved)
                                {
                                    <i style="color:lawngreen;font-size:25px;" class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i style="color:orangered;font-size:25px;" class="fa fa-times" aria-hidden="true"></i>
                                }

                            </td>
                            <td>

                                @if (item.IsHome)
                                {
                                    <i style="color:lawngreen;font-size:25px;" class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i style="color:orangered;font-size:25px;" class="fa fa-times" aria-hidden="true"></i>
                                }

                            </td>
                            <td>

                                @if (item.IsSlider)
                                {
                                    <i style="color:lawngreen;font-size:25px;" class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i style="color:orangered;font-size:25px;" class="fa fa-times" aria-hidden="true"></i>
                                }

                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Details" asp-route-id="@item.BlogId">
                                    Details
                                </a>
                                <a class="btn btn-danger btn-sm" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.BlogId">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        }
                        
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Blog did not add . . .
                </div>
            }
        </div>
    </div>
</div>

Blog.WebUI/Views/Blog/ShowMore.cshtml
@model Blog
@{
    ViewData["Title"] = "ShowMore";
}

<div class="card mb-2">
    <img class="card-img-top" style="border-radius:10%;width:500px;height:500px;" src="~/images/@Model.Image" />
    <div class="card-header">
        @Model.Title
    </div>
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text">@Model.Description</p>
        <p class="card-text">@Model.Body</p>
    </div>
</div>

Blog.WebUI/Views/Category/Create.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="container">

        <h1>Create</h1>
        <br />


        <form asp-controller="Category" asp-action="Create" method="post">

            <div class="form-group">
                <label asp-for="Name">Title</label>
                <input asp-for="Name" class="form-control" />
            </div>
         
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

Blog.WebUI/Views/Category/Delete.cshtml
@model Category
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>
    Do you want to delete
    <b>

        @Model.Name
    </b> category ?
</h1>

<form asp-controller="Category" asp-action="Delete" method="post">
    <input type="hidden" asp-for="CategoryId" />
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

Blog.WebUI/Views/Category/Details.cshtml
@model Category
@{
    ViewData["Title"] = "Details";
}

<div class="container">

    <h1>Edit</h1>
    <br />


    <form asp-controller="Category" asp-action="Details" method="post">
        <input type="hidden" asp-for="CategoryId" />
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
        </div>
      
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

Blog.WebUI/Views/Category/List.cshtml
@model IEnumerable<Category>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container mt-3">
    <div class="row">
        <h1>Category List</h1>
        <hr />
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>@item.Name</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Category" asp-action="Details" asp-route-id="@item.CategoryId">
                                        Details
                                    </a>
                                    <a class="btn btn-danger btn-sm" asp-controller="Category" asp-action="Delete" asp-route-id="@item.CategoryId">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Category did not add . . .
                </div>
            }
        </div>
    </div>
</div>

Blog.WebUI/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">Cras justo odio</li>
            <li class="list-group-item">Dapibus ac facilisis in</li>
            <li class="list-group-item">Morbi leo risus</li>
            <li class="list-group-item">Porta ac consectetur ac</li>
            <li class="list-group-item">Vestibulum at eros</li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="card">
            <img class="card-img-top" src="~/images/1.jpg" />
            <div class="card-header">
                Featured
            </div>
            <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
      

    </div>
</div>

Blog.WebUI/Views/Home/Index.cshtml
@model HomeBlogModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <div class="row">
        <div class="col-md-3">
           @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_Slider",Model.SliderBlogs)
           @Html.Partial("_BlogList",Model.HomeBlogs)
        </div>
    </div>
</div>

Blog.WebUI/Views/Home/List.cshtml
@{
    ViewData["Title"] = "List";
}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">

        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </div>

    </div>
    <div class="row">
        <div class="col-md-3">
            <ul class="list-group">
                <li class="list-group-item">Cras justo odio</li>
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item">Morbi leo risus</li>
                <li class="list-group-item">Porta ac consectetur ac</li>
                <li class="list-group-item">Vestibulum at eros</li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="card">
                <img class="card-img-top" src="~/images/1.jpg" />
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="~/images/2.jpg" />
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="~/images/3.jpg" />
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="~/images/4.jpg" />
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>

        </div>
    </div>

Blog.WebUI/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<ul class="list-group">
    @foreach (var item in Model)
    {

        <a asp-controller="Blog" asp-action="Index" asp-route-id="@item.CategoryId" class="list-group-item mt-1
           @(ViewBag.SelectedCategory==item.CategoryId.ToString()?"active":"")">
            @item.Name
        </a>
    
    }

</ul>

Blog.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">User Page <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/list">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/category/list">Category</a>
                    </li>

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container mt-3">

        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Blog.WebUI/Views/Shared/_BlogList.cshtml
@model IEnumerable<Blog>
@if (Model.Count() == 0)
{

    <div class="alert alert-warning">There is no any data . . .</div>
}
else
{
    @foreach (var item in Model)
    {
        <div class="card mb-2 mt-2">
            <img class="card-img-top" src="~/images/@item.Image" style="height:600px;width:600px;" />
            <div class="card-header">
                @item.Title
            </div>
            <div class="card-body">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">@item.Description</p>
                <a asp-controller="Blog" asp-action="ShowMore"
                   asp-route-id="@item.BlogId"
                   class="btn btn-primary">Show More</a>
            </div>
        </div>
    }
}

Blog.WebUI/Views/Shared/_SearchBox.cshtml
<form asp-controller="Blog" asp-action="Index" method="get" class="form-inline my-2 my-lg-0">
    <input id="q" name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

Blog.WebUI/Views/Shared/_Slider.cshtml
@model IEnumerable<Blog>
<div id="carouselExampleIndicators" class="carousel slide mb-3" data-ride="carousel">
    <ol class="carousel-indicators">
        @for (int i = 0; i < Model.Count(); i++)
        {
            @if (i == 0)
            {

                <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="active"></li>
            }
            else
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i"></li>

            }
        }
    </ol>
    <div class="carousel-inner" role="listbox">
        @{
            var index = 0;
        }
        @foreach (var item in Model)
        {
            if (index == 0)
            {
                ++index;
                <div class="carousel-item active">
                    <img src="~/images/@item.Image" style="width:600px;height:600px;" class="d-block w-100" alt="@item.Title" />
                    <div class="carousel-caption d-none d-md-block">
                        <h5>@item.Title</h5>
                        <p>@item.Description</p>
                    </div>
                </div>
            }
            else
            {
    <div class="carousel-item">
        <img src="~/images/@item.Image"  style="width:600px;height:600px;"
             class="d-block w-100" alt="@item.Title" />
        <div class="carousel-caption d-none d-md-block">
            <h5>@item.Title</h5>
            <p>@item.Description</p>
        </div>
    </div>
            }

        }

    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>